# Your Birth Information
name: "John Doe"
gender: "Male"
year: 1990
month: 01            # January
day: 01
hour: 12             # 12:00 PM
minute: 00
city: "New York"
nation: "US"
Timezone: "America/New_York"